#!/bin/sh

#PBS -N XYRG
#PBS -l nodes=1:ppn=12:lr2
#PBS -A ac_onsager
#PBS -l walltime=30:00:00
#PBS -q lr_batch
#PBS -e ${PBS_JOBID}.err
#PBS -o ${PBS_JOBID}.out
#PBS -V
### To start the parallel processor on the nodes you were given by the scheduler

module unload python/2.6.6
module load python/2.7.8
module unload intel/2013_sp1.4.211
module load intel/2015.0.090
module load openmpi/1.8.3-intel
module load mpi4py/1.3.1
module load mkl/2015.0.090

cd $PBS_O_WORKDIR
cpus_per_proc=1
jobname=nzhKT0.995
num_procceses=$[PBS_NUM_NODES*PBS_NUM_PPN/cpus_per_proc + 1]
echo | module list
echo "running "$num_procceses" procs with "$cpus_per_proc" cpus per proc"
export OMP_NUM_THREADS=$cpus_per_proc	
mpirun -V -v -np $num_procceses -bynode -x OMP_NUM_THREADS=$cpus_per_proc --bind-to-none --report-bindings python run_mpi.py XXZTFI $jobname



